# nazwa programu:
#PROG = wprawki00
#PROG = wprawki01
#PROG = wprawki02
#PROG = wprawki03
PROG = wprawki04
#PROG = wprawki05
#PROG = wprawki06
#PROG = wprawki07
#PROG = wprawki08
#PROG = wprawki09
#PROG = wprawki10
#PROG = wprawki11
#PROG = wprawki12
#PROG = wprawki13
#PROG = wprawki14
#PROG = wprawki15
#PROG = wprawki16
#PROG = wprawki17

# biblioteki:
LIBS = -lGL -lGLU -lglut -lm

$(PROG) : $(PROG).c
	gcc -Wall -std=c99 $(PROG).c -o $(PROG) $(LIBS)

usun :
	rm -f $(PROG) *~
